<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [1]:
!pip install pandas
!pip install matplotlib

Collecting pandas
  Downloading pandas-2.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (91 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.3.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 129.0 MB/s eta 0:00:00
Downloading numpy-2.3.1-cp312-cp312-manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 170.6 MB/s eta 0:00:00
Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.3.1 pandas-2.3.1 tzdata-2025.2
Collecting matplotlib
  Downloading matplotlib-3.10.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Downloading contourpy-1.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Downloading fonttools-4.58.5-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (106 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Downloading kiwisolver-1.4.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.2 kB)
Requirement already satisfied: numpy>=1.23 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.3.1)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (24.2)
Collecting pillow>=8 (from matplotlib)
  Downloading pillow-11.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.0 kB)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Downloading pyparsing-3.2.3-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Downloading matplotlib-3.10.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 135.5 MB/s eta 0:00:00
Downloading contourpy-1.3.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (323 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.58.5-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 156.2 MB/s eta 0:00:00
Downloading kiwisolver-1.4.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 93.8 MB/s eta 0:00:00
Downloading pillow-11.3.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 156.4 MB/s eta 0:00:00
Downloading pyparsing-3.2.3-py3-none-any.whl (111 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib
Successfully installed contourpy-1.3.2 cycler-0.12.1 fonttools-4.58.5 kiwisolver-1.4.8 matplotlib-3.10.3 pillow-11.3.0 pyparsing-3.2.3

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [16]:
import numpy as np

In [2]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
df.head()

   ResponseId                      MainBranch  ... ConvertedCompYearly JobSat
0           1  I am a developer by profession  ...                 NaN    NaN
1           2  I am a developer by profession  ...                 NaN    NaN
2           3  I am a developer by profession  ...                 NaN    NaN
3           4           I am learning to code  ...                 NaN    NaN
4           5  I am a developer by profession  ...                 NaN    NaN

[5 rows x 114 columns]

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [4]:
# Write your code here
df.dtypes

ResponseId               int64
MainBranch              object
Age                     object
Employment              object
RemoteWork              object
                        ...
JobSatPoints_11        float64
SurveyLength            object
SurveyEase              object
ConvertedCompYearly    float64
JobSat                 float64
Length: 114, dtype: object

In [6]:
df.isna()

       ResponseId  MainBranch    Age  ...  SurveyEase  ConvertedCompYearly  JobSat
0           False       False  False  ...        True                 True    True
1           False       False  False  ...        True                 True    True
2           False       False  False  ...       False                 True    True
3           False       False  False  ...       False                 True    True
4           False       False  False  ...       False                 True    True
...           ...         ...    ...  ...         ...                  ...     ...
65432       False       False  False  ...        True                 True    True
65433       False       False  False  ...        True                 True    True
65434       False       False  False  ...        True                 True    True
65435       False       False  False  ...        True                 True    True
65436       False       False  False  ...        True                 True    True

[65437 rows x 114 columns]

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [7]:
# Write your code here
df.describe()

         ResponseId      CompTotal  ...  ConvertedCompYearly        JobSat
count  65437.000000   3.374000e+04  ...         2.343500e+04  29126.000000
mean   32719.000000  2.963841e+145  ...         8.615529e+04      6.935041
std    18890.179119  5.444117e+147  ...         1.867570e+05      2.088259
min        1.000000   0.000000e+00  ...         1.000000e+00      0.000000
25%    16360.000000   6.000000e+04  ...         3.271200e+04      6.000000
50%    32719.000000   1.100000e+05  ...         6.500000e+04      7.000000
75%    49078.000000   2.500000e+05  ...         1.079715e+05      8.000000
max    65437.000000  1.000000e+150  ...         1.625660e+07     10.000000

[8 rows x 14 columns]

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [12]:
df['Country'].isna().sum()

np.int64(6507)

In [11]:
# Write your code here
df['Country'].unique()

array(['United States of America',
       'United Kingdom of Great Britain and Northern Ireland', 'Canada',
       'Norway', 'Uzbekistan', 'Serbia', 'Poland', 'Philippines',
       'Bulgaria', 'Switzerland', 'India', 'Germany', 'Ireland', 'Italy',
       'Ukraine', 'Australia', 'Brazil', 'Japan', 'Austria',
       'Iran, Islamic Republic of...', 'France', 'Saudi Arabia',
       'Romania', 'Turkey', 'Nepal', 'Algeria', 'Sweden', 'Netherlands',
       'Croatia', 'Pakistan', 'Czech Republic',
       'Republic of North Macedonia', 'Finland', 'Slovakia',
       'Russian Federation', 'Greece', 'Israel', 'Belgium', 'Mexico',
       'United Republic of Tanzania', 'Hungary', 'Argentina', 'Portugal',
       'Sri Lanka', 'Latvia', 'China', 'Singapore', 'Lebanon', 'Spain',
       'South Africa', 'Lithuania', 'Viet Nam', 'Dominican Republic',
       'Indonesia', 'Kosovo', 'Morocco', 'Taiwan', 'Georgia',
       'San Marino', 'Tunisia', 'Bangladesh', 'Nigeria', 'Liechtenstein',
       'Denmark', 'Ecuador', 'Malaysia', 'Albania', 'Azerbaijan', 'Chile',
       'Ghana', 'Peru', 'Bolivia', 'Egypt', 'Luxembourg', 'Montenegro',
       'Cyprus', 'Paraguay', 'Kazakhstan', 'Slovenia', 'Jordan',
       'Venezuela, Bolivarian Republic of...', 'Costa Rica', 'Jamaica',
       'Thailand', 'Nicaragua', 'Myanmar', 'Republic of Korea', 'Rwanda',
       'Bosnia and Herzegovina', 'Benin', 'El Salvador', 'Zimbabwe',
       'Afghanistan', 'Estonia', 'Malta', 'Uruguay', 'Belarus',
       'Colombia', 'Republic of Moldova', 'Isle of Man', 'Nomadic',
       'New Zealand', 'Palestine', 'Armenia', 'United Arab Emirates',
       'Maldives', 'Ethiopia', 'Fiji', 'Guatemala', 'Uganda',
       'Turkmenistan', 'Mauritius', 'Kenya', 'Cuba', 'Gabon', 'Bahamas',
       'South Korea', 'Iceland', 'Honduras', 'Hong Kong (S.A.R.)',
       "Lao People's Democratic Republic", 'Mongolia', 'Cambodia',
       'Madagascar', 'Angola', 'Democratic Republic of the Congo',
       'Syrian Arab Republic', 'Iraq', 'Namibia', 'Senegal', 'Kyrgyzstan',
       'Zambia', 'Swaziland', "Côte d'Ivoire", 'Kuwait', 'Tajikistan',
       'Burundi', 'Trinidad and Tobago', 'Mauritania', 'Sierra Leone',
       'Panama', 'Somalia', 'North Korea', 'Dominica', 'Guyana', 'Togo',
       'Oman', 'Barbados', 'Andorra',
       "Democratic People's Republic of Korea", 'Qatar', 'Sudan',
       'Cameroon', 'Papua New Guinea', 'Bahrain', 'Yemen', 'Malawi',
       'Burkina Faso', 'Congo, Republic of the...', 'Botswana',
       'Guinea-Bissau', 'Mozambique', 'Central African Republic',
       'Equatorial Guinea', 'Suriname', 'Belize',
       'Libyan Arab Jamahiriya', 'Cape Verde', 'Brunei Darussalam',
       'Bhutan', 'Guinea', 'Niger', 'Antigua and Barbuda', 'Mali',
       'Samoa', 'Lesotho', 'Saint Kitts and Nevis', 'Monaco',
       'Micronesia, Federated States of...', 'Haiti', nan, 'Nauru',
       'Liberia', 'Chad', 'Djibouti', 'Solomon Islands'], dtype=object)

In [14]:
df['EdLevel'].value_counts()

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          24942
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       15557
Some college/university study without earning a degree                                 7651
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     5793
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         2970
Associate degree (A.A., A.S., etc.)                                                    1793
Primary/elementary school                                                              1146
Something else                                                                          932
Name: count, dtype: int64

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [20]:
df['Country'] = df['Country'].fillna('Not specified')

In [21]:
## Write your code here
df['Country'] = df['Country'].replace({'United Kingdom of Great Britain and Northern Ireland': 'UK and Ireland', 'Iran, Islamic Republic of...':'Iran', 
                       'Venezuela, Bolivarian Republic of...':'Venezuela',"Democratic People's Republic of Korea":'Korea', 'Congo, Republic of the...':'Congo', 
                       'Micronesia, Federated States of...': 'Micronesia'})  
df['Country'].unique()

array(['United States of America', 'UK and Ireland', 'Canada', 'Norway',
       'Uzbekistan', 'Serbia', 'Poland', 'Philippines', 'Bulgaria',
       'Switzerland', 'India', 'Germany', 'Ireland', 'Italy', 'Ukraine',
       'Australia', 'Brazil', 'Japan', 'Austria', 'Iran', 'France',
       'Saudi Arabia', 'Romania', 'Turkey', 'Nepal', 'Algeria', 'Sweden',
       'Netherlands', 'Croatia', 'Pakistan', 'Czech Republic',
       'Republic of North Macedonia', 'Finland', 'Slovakia',
       'Russian Federation', 'Greece', 'Israel', 'Belgium', 'Mexico',
       'United Republic of Tanzania', 'Hungary', 'Argentina', 'Portugal',
       'Sri Lanka', 'Latvia', 'China', 'Singapore', 'Lebanon', 'Spain',
       'South Africa', 'Lithuania', 'Viet Nam', 'Dominican Republic',
       'Indonesia', 'Kosovo', 'Morocco', 'Taiwan', 'Georgia',
       'San Marino', 'Tunisia', 'Bangladesh', 'Nigeria', 'Liechtenstein',
       'Denmark', 'Ecuador', 'Malaysia', 'Albania', 'Azerbaijan', 'Chile',
       'Ghana', 'Peru', 'Bolivia', 'Egypt', 'Luxembourg', 'Montenegro',
       'Cyprus', 'Paraguay', 'Kazakhstan', 'Slovenia', 'Jordan',
       'Venezuela', 'Costa Rica', 'Jamaica', 'Thailand', 'Nicaragua',
       'Myanmar', 'Republic of Korea', 'Rwanda', 'Bosnia and Herzegovina',
       'Benin', 'El Salvador', 'Zimbabwe', 'Afghanistan', 'Estonia',
       'Malta', 'Uruguay', 'Belarus', 'Colombia', 'Republic of Moldova',
       'Isle of Man', 'Nomadic', 'New Zealand', 'Palestine', 'Armenia',
       'United Arab Emirates', 'Maldives', 'Ethiopia', 'Fiji',
       'Guatemala', 'Uganda', 'Turkmenistan', 'Mauritius', 'Kenya',
       'Cuba', 'Gabon', 'Bahamas', 'South Korea', 'Iceland', 'Honduras',
       'Hong Kong (S.A.R.)', "Lao People's Democratic Republic",
       'Mongolia', 'Cambodia', 'Madagascar', 'Angola',
       'Democratic Republic of the Congo', 'Syrian Arab Republic', 'Iraq',
       'Namibia', 'Senegal', 'Kyrgyzstan', 'Zambia', 'Swaziland',
       "Côte d'Ivoire", 'Kuwait', 'Tajikistan', 'Burundi',
       'Trinidad and Tobago', 'Mauritania', 'Sierra Leone', 'Panama',
       'Somalia', 'North Korea', 'Dominica', 'Guyana', 'Togo', 'Oman',
       'Barbados', 'Andorra', 'Korea', 'Qatar', 'Sudan', 'Cameroon',
       'Papua New Guinea', 'Bahrain', 'Yemen', 'Malawi', 'Burkina Faso',
       'Congo', 'Botswana', 'Guinea-Bissau', 'Mozambique',
       'Central African Republic', 'Equatorial Guinea', 'Suriname',
       'Belize', 'Libyan Arab Jamahiriya', 'Cape Verde',
       'Brunei Darussalam', 'Bhutan', 'Guinea', 'Niger',
       'Antigua and Barbuda', 'Mali', 'Samoa', 'Lesotho',
       'Saint Kitts and Nevis', 'Monaco', 'Micronesia', 'Haiti',
       'Not specified', 'Nauru', 'Liberia', 'Chad', 'Djibouti',
       'Solomon Islands'], dtype=object)

In [24]:
df['EdLevel'] = df['EdLevel'].fillna('Something else')
df['EdLevel'].unique()

array(['Primary/elementary school',
       'Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Some college/university study without earning a degree',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Professional degree (JD, MD, Ph.D, Ed.D, etc.)',
       'Associate degree (A.A., A.S., etc.)', 'Something else'],
      dtype=object)

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [31]:
df['Employment'].unique()

array(['Employed, full-time', 'Student, full-time',
       'Student, full-time;Not employed, but looking for work',
       'Independent contractor, freelancer, or self-employed',
       'Not employed, and not looking for work',
       'Employed, full-time;Student, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed',
       'Employed, full-time;Student, full-time', 'Employed, part-time',
       'Student, full-time;Employed, part-time',
       'Student, part-time;Employed, part-time', 'I prefer not to say',
       'Not employed, but looking for work', 'Student, part-time',
       'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed',
       'Student, full-time;Independent contractor, freelancer, or self-employed',
       'Employed, full-time;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed',
       'Student, full-time;Not employed, and not looking for work',
       'Retired',
       'Independent contractor, freelancer, or self-employed;Student, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time',
       'Not employed, but looking for work;Student, part-time',
       'Not employed, but looking for work;Not employed, and not looking for work',
       'Independent contractor, freelancer, or self-employed;Retired',
       'Not employed, but looking for work;Student, part-time;Employed, part-time',
       'Student, full-time;Not employed, but looking for work;Not employed, and not looking for work',
       'Employed, full-time;Not employed, but looking for work',
       'Student, full-time;Not employed, and not looking for work;Student, part-time',
       'Employed, full-time;Retired',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Not employed, but looking for work;Employed, part-time',
       'Employed, full-time;Student, full-time;Employed, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Not employed, and not looking for work;Student, part-time',
       'Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Student, full-time;Student, part-time',
       'Student, full-time;Not employed, but looking for work;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Retired',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed',
       'Employed, full-time;Student, full-time;Student, part-time',
       'Not employed, but looking for work;Retired',
       'Employed, full-time;Student, full-time;Not employed, but looking for work',
       'Not employed, and not looking for work;Retired',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Retired',
       'Employed, full-time;Not employed, but looking for work;Employed, part-time',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time',
       'Student, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time;Employed, part-time;Retired',
       'Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed',
       'Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time',
       'Student, full-time;Not employed, but looking for work;Retired',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time',
       'Student, part-time;Retired',
       'Student, full-time;Not employed, but looking for work;Not employed, and not looking for work;Student, part-time',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Retired',
       'Employed, full-time;Student, full-time;Student, part-time;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Student, full-time;Not employed, but looking for work;Employed, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Student, part-time;Retired',
       'Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Retired',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time',
       'Independent contractor, freelancer, or self-employed;Employed, part-time;Retired',
       'Employed, full-time;Not employed, and not looking for work',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Retired',
       'Student, full-time;Student, part-time;Employed, part-time',
       'Employed, part-time;Retired',
       'Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time;Retired',
       'Employed, full-time;Student, part-time;Employed, part-time',
       'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired',
       'Student, full-time;Student, part-time;Retired',
       'Student, full-time;Not employed, and not looking for work;Employed, part-time',
       'Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Not employed, but looking for work;Not employed, and not looking for work;Student, part-time;Employed, part-time',
       'Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time',
       'Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time;Employed, part-time',
       'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time',
       'Not employed, and not looking for work;Employed, part-time',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Student, part-time',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time',
       'Employed, full-time;Not employed, but looking for work;Not employed, and not looking for work;Employed, part-time',
       'Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time;Retired',
       'Not employed, but looking for work;Student, part-time;Retired',
       'Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time;Retired',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed',
       'Not employed, but looking for work;Not employed, and not looking for work;Student, part-time',
       'Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Retired',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Student, part-time;Employed, part-time',
       'Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time',
       'Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time;Retired',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time',
       'Student, full-time;Retired',
       'Employed, full-time;Not employed, but looking for work;Student, part-time',
       'Not employed, and not looking for work;Student, part-time;Employed, part-time',
       'Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Retired'],
      dtype=object)

In [36]:
## Write your code here
df['Employment'] = df['Employment'].apply(lambda x: 'Employed' if x.startswith('Employed') else x)
df['Employment'] = df['Employment'].apply(lambda x: 'Not employed' if x.startswith('Not employed') else x)
df['Employment'] = df['Employment'].apply(lambda x: 'Student' if x.startswith('Student') else x)
df['Employment'] = df['Employment'].apply(lambda x: 'Independent contractor' if x.startswith('Independent contractor') else x)

In [37]:
df['Employment'].unique()

array(['Employed', 'Student', 'Independent contractor', 'Not employed',
       'I prefer not to say', 'Retired'], dtype=object)

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [42]:
## Write your code here
df.isnull().sum().sort_values(ascending=False)

AINextMuch less integrated    64289
AINextLess integrated         63082
AINextNo change               52939
AINextMuch more integrated    51999
EmbeddedAdmired               48704
                              ...
Age                               0
EdLevel                           0
Check                             0
Employment                        0
ResponseId                        0
Length: 114, dtype: int64

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [43]:
## Write your code here
df['ConvertedCompYearly'] = df['ConvertedCompYearly'].fillna(df['ConvertedCompYearly'].mean())

In [44]:
df['ConvertedCompYearly'].isna().sum()

np.int64(0)

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [45]:
## Write your code here
df['RemoteWork'] = df['RemoteWork'].fillna(df['RemoteWork'].mode().iloc[0])

In [46]:
df['RemoteWork'].isna().sum()

np.int64(0)

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [47]:
## Write your code here
df['ConvertedCompYearly'] = (df['ConvertedCompYearly'] - df['ConvertedCompYearly'].min())/(df['ConvertedCompYearly'].max() - df['ConvertedCompYearly'].min())

In [48]:
df['ConvertedCompYearly']

0        0.0053
1        0.0053
2        0.0053
3        0.0053
4        0.0053
          ...
65432    0.0053
65433    0.0053
65434    0.0053
65435    0.0053
65436    0.0053
Name: ConvertedCompYearly, Length: 65437, dtype: float64

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [49]:
## Write your code here
df['ConvertedCompYearly' ] = np.log10(df['ConvertedCompYearly'])

/opt/conda/lib/python3.12/site-packages/pandas/core/arraylike.py:399: RuntimeWarning: divide by zero encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [55]:
## Write your code here
df['YearsCodePro'] = df['YearsCodePro'].replace({np.nan: '0', 'Less than 1 year': '0', 'More than 50 years':'50'})

In [58]:
df['YearsCodePro'] = df['YearsCodePro'].astype('int')

In [64]:
groups = ['Between 0 to 10 years', 'Between 10 to 20 years', 'Between 20 to 30 years', 'Between 30 to 40 years', 'Above 40 years']
bins = np.linspace(min(df['YearsCodePro']), max(df['YearsCodePro']), 6)

df['ExperienceLevel'] = pd.cut(df['YearsCodePro'], bins, labels=groups, include_lowest=True)

In [65]:
df.head()

   ResponseId                      MainBranch  ... JobSat         ExperienceLevel
0           1  I am a developer by profession  ...    NaN   Between 0 to 10 years
1           2  I am a developer by profession  ...    NaN  Between 10 to 20 years
2           3  I am a developer by profession  ...    NaN  Between 20 to 30 years
3           4           I am learning to code  ...    NaN   Between 0 to 10 years
4           5  I am a developer by profession  ...    NaN   Between 0 to 10 years

[5 rows x 115 columns]

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.